### ISSUE TITLE
App functions with special characters in the parameters are failing

### ISSUE THREAD

**Issue by malinaa96** [acivitillo/giotto#20]
Right now special characters in URL queries are not replaced and for example '+' is treated as a space which causes differences in parameters values and errors as a result.

https://docs.python.org/3/library/urllib.parse.html#url-quoting

Thanks @pattrycja96 for finding this bug.

**Comment by pattrycja96** [comment]
Welcome Kasia 🚀 😆

**Comment by malinaa96** [comment]
Fixed
